<?php
/**
 * TL_ROOT/system/modules/teaserimages/languages/it/default.php 
 * 
 * Contao extension: teaserimages 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : Tim Gatzky 2011-2012 
 * License   : LGPL 
 * Author    : Tim Gatzky (Timmm), http://www.tim-gatzky.de 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['teaser']['0'] = "Testo introduttivo";
$GLOBALS['TL_LANG']['tl_content']['teaser_addImage']['0'] = "Aggiungi immagine";
$GLOBALS['TL_LANG']['tl_content']['teaser_addImage']['1'] = "Aggiungi un'immagine al teaser.";
$GLOBALS['TL_LANG']['tl_content']['addImage']['0'] = "Aggiungi un'immagine";
$GLOBALS['TL_LANG']['tl_content']['addImage']['1'] = "Aggiungi un'immagine al contenuto.";
$GLOBALS['TL_LANG']['tl_content']['singleSRC']['0'] = "File sorgente";
$GLOBALS['TL_LANG']['tl_content']['singleSRC']['1'] = "Si prega di selezionare un file o una cartella dalla directory file.";
$GLOBALS['TL_LANG']['tl_content']['alt']['0'] = "Testo alternativo";
$GLOBALS['TL_LANG']['tl_content']['alt']['1'] = "Un sito web accessibile dovrebbe sempre fornire un testo alternativo per le immagini e i filmati con una breve descrizione del loro contenuto.";
$GLOBALS['TL_LANG']['tl_content']['size']['0'] = "Larghezza e altezza immagine";
$GLOBALS['TL_LANG']['tl_content']['size']['1'] = "Qui puoi impostare le dimensioni dell'immagine e il metodo di ridimensionamento.";
$GLOBALS['TL_LANG']['tl_content']['imagemargin']['0'] = "Margine immagine";
$GLOBALS['TL_LANG']['tl_content']['imagemargin']['1'] = "Qui puoi specificare il margine superiore, destro, inferiore e sinistro.";
$GLOBALS['TL_LANG']['tl_content']['imageUrl']['0'] = "Link di destinazione dell'immagine";
$GLOBALS['TL_LANG']['tl_content']['imageUrl']['1'] = "Un link di destinazione dell'immagine personalizzato sovrascriverà il link lightbox, l'immagine non potrà quindi più essere visibile a dimensione intera.";
$GLOBALS['TL_LANG']['tl_content']['fullsize']['0'] = "Visione a dimensione intera/in una nuova finestra";
$GLOBALS['TL_LANG']['tl_content']['fullsize']['1'] = "Apre l'immagine a dimensione intera in una finestra lightbox o il link in una nuova finestra del browser.";
$GLOBALS['TL_LANG']['tl_content']['floating']['0'] = "Allineamento immagine";
$GLOBALS['TL_LANG']['tl_content']['floating']['1'] = "Prego specificare come allineare l'immagine.";
$GLOBALS['TL_LANG']['tl_content']['caption']['0'] = "Didascalia dell'immagine";
$GLOBALS['TL_LANG']['tl_content']['caption']['1'] = "Qui puoi inserire un breve testo che verrà mostrato sotto l'immagine";
$GLOBALS['TL_LANG']['tl_article']['teaser_linkedimage']['0'] = "Linka l'immagine";
$GLOBALS['TL_LANG']['tl_article']['teaser_linkedimage']['1'] = "Linka l'immagine teaser a questo articolo.";
$GLOBALS['TL_LANG']['tl_news']['teaser_linkedimage']['0'] = "Linka l'immagine";
$GLOBALS['TL_LANG']['tl_news']['teaser_linkedimage']['1'] = "Linka l'immagine teaser a questo post.";
$GLOBALS['TL_LANG']['tl_calender_events']['teaser_linkedimage']['0'] = "Linka l'immagine";
$GLOBALS['TL_LANG']['tl_calender_events']['teaser_linkedimage']['1'] = "Linka l'immagine teaser a questo evento.";
 
?>
