<?php
/**
 * TL_ROOT/system/modules/teaserimages/languages/it/tl_settings.php 
 * 
 * Contao extension: teaserimages 1.0.0 stable 
 * Italian translation file 
 * 
 * Copyright : Tim Gatzky 2011-2012 
 * License   : LGPL 
 * Author    : Tim Gatzky (Timmm), http://www.tim-gatzky.de 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['teaser_news_tinymce']['0'] = "Utilizza TinyMCE per i teaser news";
$GLOBALS['TL_LANG']['tl_settings']['teaser_news_tinymce']['1'] = "Utilizza l'editor TinyMCE al posto del normale campo di testo per il testo introduttivo delle news.";
$GLOBALS['TL_LANG']['tl_settings']['teaser_events_tinymce']['0'] = "Utilizza TinyMCE per i teaser eventi";
$GLOBALS['TL_LANG']['tl_settings']['teaser_events_tinymce']['1'] = "Utilizza l'editor TinyMCE al posto del normale campo di testo per il testo introduttivo degli eventi.";
$GLOBALS['TL_LANG']['tl_settings']['teaser_articles_tinymce']['0'] = "Utilizza TinyMCE per i teaser articoli";
$GLOBALS['TL_LANG']['tl_settings']['teaser_articles_tinymce']['1'] = "Utilizza l'editor TinyMCE al posto del normale campo di testo per il testo introduttivo degli articoli.";
$GLOBALS['TL_LANG']['tl_settings']['teaser_settings_legend'] = "Impostazioni teaser";
 
?>
