<?php
/**
 * TL_ROOT/system/modules/teaserimages/languages/fr/tl_settings.php 
 * 
 * Contao extension: teaserimages 1.0.0 beta1 
 * French translation file 
 * 
 * Copyright : Tim Gatzky 2011 
 * License   : LGPL 
 * Author    : Tim Gatzky (Timmm), www.tim-gatzky.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['teaser_news_tinymce']['0'] = "Utiliser TinyMCE pour les accroches des actualités";
$GLOBALS['TL_LANG']['tl_settings']['teaser_news_tinymce']['1'] = "Utiliser l'éditeur TinyMCE au lieu du champ texte courant de l'accroche des actualités.";
$GLOBALS['TL_LANG']['tl_settings']['teaser_events_tinymce']['0'] = "Utiliser TinyMCE pour les accroches des événements";
$GLOBALS['TL_LANG']['tl_settings']['teaser_events_tinymce']['1'] = "Utiliser l'éditeur TinyMCE au lieu du champ texte courant de l'accroche des événements.";
$GLOBALS['TL_LANG']['tl_settings']['teaser_articles_tinymce']['0'] = "Utiliser TinyMCE pour les accroches des articles";
$GLOBALS['TL_LANG']['tl_settings']['teaser_articles_tinymce']['1'] = "Utiliser l'éditeur TinyMCE au lieu du champ texte courant de l'accroche des articles.";
$GLOBALS['TL_LANG']['tl_settings']['teaser_settings_legend'] = "Préférences des accroches";
 
?>
