<?php
/**
 * TL_ROOT/system/modules/teaserimages/languages/fr/default.php 
 * 
 * Contao extension: teaserimages 1.0.0 beta1 
 * French translation file 
 * 
 * Copyright : Tim Gatzky 2011 
 * License   : LGPL 
 * Author    : Tim Gatzky (Timmm), www.tim-gatzky.de 
 * Translator: Lionel Maccaud (lionel), http://www.synergie-consulting.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['teaser']['0'] = "Texte de l'accroche";
$GLOBALS['TL_LANG']['tl_content']['teaser_addImage']['0'] = "Ajouter une image";
$GLOBALS['TL_LANG']['tl_content']['teaser_addImage']['1'] = "Ajouter une image à l'accroche.";
$GLOBALS['TL_LANG']['tl_content']['addImage']['0'] = "Ajouter une image";
$GLOBALS['TL_LANG']['tl_content']['addImage']['1'] = "Ajouter une image à l'élément de contenu.";
$GLOBALS['TL_LANG']['tl_content']['singleSRC']['0'] = "Fichier source";
$GLOBALS['TL_LANG']['tl_content']['singleSRC']['1'] = "Sélectionner un fichier à partir de l'explorateur de fichiers.";
$GLOBALS['TL_LANG']['tl_content']['alt']['0'] = "Texte alternatif";
$GLOBALS['TL_LANG']['tl_content']['alt']['1'] = "Un site internet accessible doit toujours fournir un texte alternatif pour les images et les films qui sera une courte description de leur contenu.";
$GLOBALS['TL_LANG']['tl_content']['size']['0'] = "Largeur et hauteur de l'image";
$GLOBALS['TL_LANG']['tl_content']['size']['1'] = "Saisir les dimensions de l'image et le mode de redimensionnement.";
$GLOBALS['TL_LANG']['tl_content']['imagemargin']['0'] = "Marge de l'image";
$GLOBALS['TL_LANG']['tl_content']['imagemargin']['1'] = "Saisir la marge supérieure, droite, inférieure et gauche.";
$GLOBALS['TL_LANG']['tl_content']['imageUrl']['0'] = "Cible du lien";
$GLOBALS['TL_LANG']['tl_content']['imageUrl']['1'] = "Il ne sera pas possible de voir l'image en taille réelle si vous utilisez une cible de lien personnalisée.";
$GLOBALS['TL_LANG']['tl_content']['fullsize']['0'] = "Vue en taille réelle / nouvelle fenêtre";
$GLOBALS['TL_LANG']['tl_content']['fullsize']['1'] = "Afficher l'image en pleine taille si l'on clique dessus, avec un effet lightbox, ou dans une nouvelle fenêtre du navigateur.";
$GLOBALS['TL_LANG']['tl_content']['floating']['0'] = "Alignement de l'image";
$GLOBALS['TL_LANG']['tl_content']['floating']['1'] = "Spécifier comment aligner l'image.";
$GLOBALS['TL_LANG']['tl_content']['caption']['0'] = "Légende de l'image";
$GLOBALS['TL_LANG']['tl_content']['caption']['1'] = "Saisir un court texte qui s'affichera au-dessous de l'image.";
$GLOBALS['TL_LANG']['tl_article']['teaser_linkedimage']['0'] = "Lien de l'image";
$GLOBALS['TL_LANG']['tl_article']['teaser_linkedimage']['1'] = "Lier l'image de l'accroche à l'article";
$GLOBALS['TL_LANG']['tl_news']['teaser_linkedimage']['0'] = "Lien de l'image";
$GLOBALS['TL_LANG']['tl_news']['teaser_linkedimage']['1'] = "Lier l'image de l'accroche à l'actualité";
$GLOBALS['TL_LANG']['tl_calender_events']['teaser_linkedimage']['0'] = "Lien de l'image";
$GLOBALS['TL_LANG']['tl_calender_events']['teaser_linkedimage']['1'] = "Lier l'image de l'accroche à l'événement";
 
?>
